# Generated by Django 4.1.1 on 2022-09-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordetail',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='sensordetail',
            name='sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mensurements', to='measurement.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Датчик'),
        ),
        migrations.AlterField(
            model_name='sensordetail',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Температура'),
        ),
    ]
