# Generated by Django 4.1.1 on 2022-09-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_rename_data_sensordetail_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordetail',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensurements', to='measurement.sensor'),
        ),
    ]
